{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "DocumentFailureMessage"
	},
	"Message": "#ActionResults:DownloadDocument/error",
	"Title": "$(L,'xmsg_document_failure')",
	"OKCaption": "$(L,'xbut_ok')"
}