{
	"_Type": "Action.Type.OpenDocument",
	"ActionResult": {
		"_Name": "OpenDocument"
	},
	 "Path": "/driverapp/Services/attachmentdwld.service/{@odata.readLink}/$value",
	 "MimeType": "{MimeType}",
	 "UseExternalViewer": true
}