{
	"_Type": "Action.Type.ODataService.Initialize",
	"ActionResult": {
		"_Name": "init"
	},
	"OnFailure": "/driverapp/Actions/attachmentdwld/Service/InitializeOfflineFailureMessage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Downloading actions...",
	"Service": "/driverapp/Services/attachmentdwld.service",
	"DefiningRequests": [
		{
			"Name": "AttachmentDwld",
			"Query": "AttachmentDwld"
		}
	]
}