{
    "Service": "/driverapp/Services/main.service",
    "DefiningRequests": [{
            "Name": "ZTM_C_DDL_DA_ROOT",
            "Query": "ZTM_C_DDL_DA_ROOT?$filter=drv_email1 eq '{{#Application/#AppData/UserId}}' or drv_email2 eq '{{#Application/#AppData/UserId}}'"
        },
        {
            "Name": "ZTM_I_DDL_DA_ATTC",
            "Query": "ZTM_I_DDL_DA_ATTC?$filter=drv_email1 eq '{{#Application/#AppData/UserId}}' or drv_email2 eq '{{#Application/#AppData/UserId}}'"
        },
        {
            "Name": "ZTM_I_DDL_DA_EVTL",
            "Query": "ZTM_I_DDL_DA_EVTL?$filter=drv_email1 eq '{{#Application/#AppData/UserId}}' or drv_email2 eq '{{#Application/#AppData/UserId}}'"
        },
        {
            "Name": "ZTM_I_DDL_DA_STIT",
            "Query": "ZTM_I_DDL_DA_STIT?$filter=drv_email1 eq '{{#Application/#AppData/UserId}}' or drv_email2 eq '{{#Application/#AppData/UserId}}'"
        },
        {
            "Name": "ZTM_I_DDL_DA_STOP",
            "Query": "ZTM_I_DDL_DA_STOP?$filter=drv_email1 eq '{{#Application/#AppData/UserId}}' or drv_email2 eq '{{#Application/#AppData/UserId}}'"
        },
                {
            "Name": "ZTM_I_DDL_DA_DLVIT",
            "Query": "ZTM_I_DDL_DA_DLVIT?$filter=drv_email1 eq '{{#Application/#AppData/UserId}}' or drv_email2 eq '{{#Application/#AppData/UserId}}'"
        },
        {
            "Name": "ZTM_I_DDL_DA_FUIT",
            "Query": "ZTM_I_DDL_DA_FUIT?$filter=drv_email1 eq '{{#Application/#AppData/UserId}}' or drv_email2 eq '{{#Application/#AppData/UserId}}'"
        }
    ],
    "_Type": "Action.Type.OfflineOData.Download",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnFailure": "/driverapp/Actions/main/Service/SyncFailureMessage.action",
    "OnSuccess": "/driverapp/Rules/main/ErrorArchive_CheckForSyncError.js"
}