{
    "Service": "/driverapp/Services/main.service",
    "DefiningRequests": [{
            "Name": "ZTM_C_DDL_DA_ROOT",
            "Query": "ZTM_C_DDL_DA_ROOT"
        },
        {
            "Name": "ZTM_I_DDL_DA_ATTC",
            "Query": "ZTM_I_DDL_DA_ATTC"
        },
        {
            "Name": "ZTM_I_DDL_DA_EVTL",
            "Query": "ZTM_I_DDL_DA_EVTL"
        },
        {
            "Name": "ZTM_I_DDL_DA_STIT",
            "Query": "ZTM_I_DDL_DA_STIT"
        },
        {
            "Name": "ZTM_I_DDL_DA_STOP",
            "Query": "ZTM_I_DDL_DA_STOP"
        },
        {
            "Name": "ZTM_I_DDL_DA_DLVIT",
            "Query": "ZTM_I_DDL_DA_DLVIT"
        }
    ],
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText": "Downloading Shipments...",
    "ActionResult": {
        "_Name": "init"
    },
    "OnFailure": "/driverapp/Actions/main/Service/InitializeOfflineFailureMessage.action"
}